title:       "Operating Systems 2021-1 (OS211)"
copyright:   "2021"
author:           "Azka Fitria"
urlweb:           "https://azkafitria.github.io/os211/"
urlgithub:        "https://github.com/azkafitria/os211/"
urlghpage:        "https://azkafitria.github.io/os211/"
github:           [metadata]